[package]
name = "russ-internal"
version = "0.1.0"
authors = ["Simon Berger <simon@siku2.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
russ-internal-macro = { path = "../russ-internal-macro" }
