use super::{
    numeric::{Angle, Number, Percentage},
    textual::{CssIdent, CssString},
};
use russ_internal_macro::vds;

vds! {
    <"color"> = <hex-color> | <named-color> | currentcolor | transparent |
                <rgb-fn> | <hsl-fn> | <hwb-fn> |
                <lab-fn> | <lch-fn> | <gray-fn> |
                <color-fn> | <device-cmyk-fn> |
                <system-color>;

    // common values
    <alpha-value> = <number> | <percentage>;
    <hue> = <number> | <angle>;

    <rgb-fn> = "rgb"( <percentage>{3} [ "/" <alpha-value> ]? ) |
               "rgb"( <number>{3} [ "/" <alpha-value> ]? );
    <hsl-fn> = "hsl"( <hue> <percentage> <percentage> [ "/" <alpha-value> ]? );
    <hwb-fn> = "hwb"( <hue> <percentage> <percentage> [ "/" <alpha-value> ]? );

    <lab-fn> = "lab"( <percentage> <number> <number> [ "/" <alpha-value> ]? );
    <lch-fn> = "lch"( <percentage> <number> <hue> [ "/" <alpha-value> ]? );
    <gray-fn> = "gray"( <number>  [ "/" <alpha-value> ]? );

    <color-fn> = "color"( [ <css-ident>? [ <number>+ | <css-string> ] [ "/" <alpha-value> ]? ]# , <color in Box>? );
    <device-cmyk-fn> = "device-cmyk"( <cmyk-component>{4} [ "/" <alpha-value> ]? , <color in Box>? );
    <cmyk-component> = <number> | <percentage>;
}

vds! {
    <named-color> = "aliceblue"
        | "antiquewhite"
        | "aqua"
        | "aquamarine"
        | "azure"
        | "beige"
        | "bisque"
        | "black"
        | "blanchedalmond"
        | "blue"
        | "blueviolet"
        | "brown"
        | "burlywood"
        | "cadetblue"
        | "chartreuse"
        | "chocolate"
        | "coral"
        | "cornflowerblue"
        | "cornsilk"
        | "crimson"
        | "cyan"
        | "darkblue"
        | "darkcyan"
        | "darkgoldenrod"
        | "darkgray"
        | "darkgreen"
        | "darkgrey"
        | "darkkhaki"
        | "darkmagenta"
        | "darkolivegreen"
        | "darkorange"
        | "darkorchid"
        | "darkred"
        | "darksalmon"
        | "darkseagreen"
        | "darkslateblue"
        | "darkslategray"
        | "darkslategrey"
        | "darkturquoise"
        | "darkviolet"
        | "deeppink"
        | "deepskyblue"
        | "dimgray"
        | "dimgrey"
        | "dodgerblue"
        | "firebrick"
        | "floralwhite"
        | "forestgreen"
        | "fuchsia"
        | "gainsboro"
        | "ghostwhite"
        | "gold"
        | "goldenrod"
        | "gray"
        | "green"
        | "greenyellow"
        | "grey"
        | "honeydew"
        | "hotpink"
        | "indianred"
        | "indigo"
        | "ivory"
        | "khaki"
        | "lavender"
        | "lavenderblush"
        | "lawngreen"
        | "lemonchiffon"
        | "lightblue"
        | "lightcoral"
        | "lightcyan"
        | "lightgoldenrodyellow"
        | "lightgray"
        | "lightgreen"
        | "lightgrey"
        | "lightpink"
        | "lightsalmon"
        | "lightseagreen"
        | "lightskyblue"
        | "lightslategray"
        | "lightslategrey"
        | "lightsteelblue"
        | "lightyellow"
        | "lime"
        | "limegreen"
        | "linen"
        | "magenta"
        | "maroon"
        | "mediumaquamarine"
        | "mediumblue"
        | "mediumorchid"
        | "mediumpurple"
        | "mediumseagreen"
        | "mediumslateblue"
        | "mediumspringgreen"
        | "mediumturquoise"
        | "mediumvioletred"
        | "midnightblue"
        | "mintcream"
        | "mistyrose"
        | "moccasin"
        | "navajowhite"
        | "navy"
        | "oldlace"
        | "olive"
        | "olivedrab"
        | "orange"
        | "orangered"
        | "orchid"
        | "palegoldenrod"
        | "palegreen"
        | "paleturquoise"
        | "palevioletred"
        | "papayawhip"
        | "peachpuff"
        | "peru"
        | "pink"
        | "plum"
        | "powderblue"
        | "purple"
        | "rebeccapurple"
        | "red"
        | "rosybrown"
        | "royalblue"
        | "saddlebrown"
        | "salmon"
        | "sandybrown"
        | "seagreen"
        | "seashell"
        | "sienna"
        | "silver"
        | "skyblue"
        | "slateblue"
        | "slategray"
        | "slategrey"
        | "snow"
        | "springgreen"
        | "steelblue"
        | "tan"
        | "teal"
        | "thistle"
        | "tomato"
        | "turquoise"
        | "violet"
        | "wheat"
        | "white"
        | "whitesmoke"
        | "yellow"
        | "yellowgreen";
}
